language: objective-c

xcode_workspace: JCSegueUserInfo.xcworkspace
xcode_scheme: JCSegueUserInfo

before_script:
  - export LANG=en_US.UTF-8

before_install: 
  - brew unlink xctool
  - brew update
  - brew install xctool --HEAD
  - gem install cocoapods

script: xctool -workspace JCSegueUserInfo.xcworkspace -scheme JCSegueUserInfo test -sdk iphonesimulator
